README.md

Added ODR-mmtools (continuation of CRC-mmbtools) to Software defined radio section.
Added GPAC to multimedia players section.
New Radio production, Audio over IP sections.

Updated list, added section

---

README.md

We have been using its CLI utils, and it's API for years at Vimeo. I cannot recommend it enough.

Add L-SMASH

---

README.md

And remove spurious white lines.

Update description of EBU-TT-D in dash.js

---

README.md

add CCExtractor

---

README.md

Surprised to see that it wasn't mentioned here - but perhaps that's for a reason previously discussed elsewhere?

Added MXFLib to Multimedia content processing

---

README.md

Samsung recently announced this one.

Add HbbPlayer

---

README.md

As discussed with Michael Barroco, here is the pull request to add the entry for Turing codec in the codecs section.

Added an entry for the Turing codec under codecs

---

README.md

Updates DVB Inspector link. Tnx to https://github.com/craftbyte

update link closes #63

---

README.md

Add SubtitleEdit - Credits @MarcoNPO

---

README.md

Added dvbshout

---

README.md

- add missing hyphen in project names
- ODR recently reachable via HTTPS

Fix SDR links

---

README.md

Add Icecast audio and video over server software

Add Icecast

---

README.md

Added ts2mpa

---

README.md

Added Jack Meter to Monitoring & Quality Control

---

README.md

[TSDuck](https://tsduck.github.io/) is an extensible toolkit for MPEG/DVB transport streams for test, monitoring, integration debug, lab, demo and more.

Added TSDuck MPEG TS toolkit

---

README.md

Hi @frans-ebu 
Thanks for your response (#106).

Add c-bata/rtmp

---

README.md

Add NMOS CPP and SDPoker

---

README.md

I don't know if there's a better name for this category?

Add Teleprompter

---

README.md

Blocked behind #119 .
I'm not sure if this should go in here, or Monitoring & QC or elsewhere (a new category)? It would also be of use for Radio/Audio Production.

Add PiClock

---

README.md

Not sure about the "TV Production" category, just adopted the "Radio Production" one, as it seemed to be the most content/workflow oriented.

Adds MOS-connection

---

README.md

Kind of a self promotion, but I think it fits very well ;)

Add MIDIMonster to the list

---

README.md

These are the link fixes found via https://github.com/ebu/awesome-broadcasting/pull/141 which are hopefully less controversial and can just be merged in while any politics for Travis is being resolved.

Fix a number of broken links

---

README.md

python and ffmpeg based playout from folder or playlists

add ffplayout

---

README.md

Add BBC/Brave to Multimedia content processing.
Basic Real-time AV Editor (Brave) - lets you preview, mix, and route live audio and video streams on the cloud.

Add BBC/Brave

---

README.md

Create a new category and move PiClock into it too

Add PiRSClock-Full

---

README.md

Add OnAirScreen

---

README.md

Not certain this is the correct category.

Add sony/nmos-cpp and nmos-js

---

README.md

Surprised this is not included already! :-)
@pedro-alves-ferreira

Add ebu/pi-list

---

README.md

Third PR adding NMOS open-source projects.
Should these have their own category?

Add AMWA-TV/nmos-testing

---

README.md

Affordable tally lights using free open source software and low cost hardware.

Add TallyArbiter.com

---

README.md

Adding Control Systems section and Lawo Ember Plus github link.

New Section, Control Systems

---

README.md

Docker container with Registry and Controller, IS-04/05/08/07/09, BCP-003-01

Add NVIDIA NMOS Docker Container

---

README.md

It was suggested we submit our automatic vision mixing solution for ATEM. We've been using this in production for 5 years and it's proven rock solid. We hope other radio broadcasters can make use of it to build their own low-cost visual radio systems. I wasn't entirely sure which heading it would best fit under so please feel free to correct me!

Add Insanity Radio's automix project

---

README.md

Hi there, I've added a new project - BUG. 
A simple control system with browser based interface recently open sourced at the BBC.
You can find more details here - https://github.com/bbc/bug

Added New Project: BUG

---

README.md

It's a fork of PiRSClock-Full but with some usefull changes.
Changed Layout, added fields, added talktimer and network capabilities to change on air source and song-info.

Added a new Studioscreen

---

README.md

Addition of the DELTACAST open-source NMOS samples based on nmos-cpp

Add DELTACAST open-source NMOS samples

---

README.md

add Examples of SMPTE ST 2110 pcap files from Disney NEO AdvancedTechnology

add Examples of SMPTE ST 2110 pcap files from Disney

---

README.md

https://github.com/ebu/awesome-broadcasting/issues/192

Create Rundown automation section with Ontime and SuperConductor
